# Site settings
title: Zekun Blog
SEOTitle: Zekun Wang's Blog | Data Science
header-img: img/bg-ice.jpg
email: zekun.wang.us@gmail.com
description: "Across the Great Wall, we can reach every corner in the world"
keyword: "ZW, Zekun Blog, 王泽坤的博客, zekunwang, 王泽坤, data science, DS"
url: "http://waittim.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/waittim/waittim.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Zekun Wang"
sidebar-avatar: /img/Zekun_Wang_icon.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:
zhihu_username:
github_username: waittim
facebook_username:
jianshu_username:
#twitter_username:




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: waittim

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 491d9ec79c30f63d6dfb                            #生成的clientID
  clientSecret: e00b92b47fb3a2f6d0bf024cea6ef6a0fc44e165    #生成的clientSecret
  repo: waittim.github.io    #仓库名称
  owner: waittim    #github用户名
  admin: waittim
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-154878163-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "Data Science | Vanderbilt",
        href: "https://www.vanderbilt.edu/datascience/"
    },{
        title: "Vanderbilt Univeristy",
        href: "https://www.vanderbilt.edu/"
    },{
        title: "LinkedIn | Zekun Wang",
        href: "https://www.linkedin.com/in/zekun-wang/"
    }
]
